### ISSUE TITLE
Is the loss trend normal?

### ISSUE THREAD

**Issue by cloudcjf** [mikacuy/pointnetvlad#15]
@mikacuy Hi，mika. First of all, thanks for your great work. I'm new to place recognition tasks and trying to retrain your network as a tutorial. I used to retrain some other networks and the losses go almost down directly while the loss defined in your network keeps going up and down. Here is a screenshot which I log out the batch losses. So does it go the right way as you did before? Tell me if I miss any details. Thanks 
![image](https://user-images.githubusercontent.com/54716067/114973434-0e3ac800-9eb3-11eb-8518-7fcf731611fc.png)

Claude Cui

**Comment by Master-cai** [comment]
> 

hi, I have the same question, do you have any idea about that? thanks!

**Comment by cloudcjf** [comment]
> > 
> 
> hi, I have the same question, do you have any idea about that? thanks!

The place recognition task adopted the triplet loss and Hinger loss to backpropagate the parameters. The zero-loss means that the distance between the anchor and positive point cloud in this tuple is already less than the anchor and negative point cloud.

**Comment by Master-cai** [comment]
> > > 
> > 
> > 
> > hi, I have the same question, do you have any idea about that? thanks!
> 
> The place recognition task adopted the triplet loss and Hinger loss to backpropagate the parameters. The zero-loss means that the distance between the anchor and positive point cloud in this tuple is already less than the anchor and negative point cloud.

thanks a lot! 

If you don't mind, I have another question: I find in the file "train_pointnetvlad", the global variable "HARD_NEGATIVES={}" is never updated which means it is useless, is there something wrong here?

**Comment by cloudcjf** [comment]
> > > > 
> > > 
> > > 
> > > hi, I have the same question, do you have any idea about that? thanks!
> > 
> > 
> > The place recognition task adopted the triplet loss and Hinger loss to backpropagate the parameters. The zero-loss means that the distance between the anchor and positive point cloud in this tuple is already less than the anchor and negative point cloud.
> 
> thanks a lot!
> 
> If you don't mind, I have another question: I find in the file "train_pointnetvlad", the global variable "HARD_NEGATIVES={}" is never updated which means it is useless, is there something wrong here?

Yes, if you just follow the default settings, it will never be updated
