### ISSUE TITLE
A simple question about the dataset

### ISSUE THREAD

**Issue by songjiaxina** [mikacuy/pointnetvlad#4]
Hi, thanks for your code and dataset. Could you please tell me the difference between the  folder called  pointcloud_20m_10overlap and the folder called  pointcloud_20m?

**Comment by mikacuy** [comment]
Hi @songjiaxina , the difference is pointcloud_20m/ contain mutually disjoint submaps, while there is a 50% overlap in pointcloud_20m_10overlap/. That is in pointcloud_20m_10overlap/, the centroids of two consecutive submaps are 10m apart. In both folders, each submap is a 20m trajectory of the car. pointcloud_20m_10overlap/ is used for training while mutually disjoint pointcloud_20m/ is used for evaluation.

**Comment by songjiaxina** [comment]
OK! Thanks for your answer！
