### ISSUE TITLE
Question about generating the dataset

### ISSUE THREAD

**Issue by JuanDuGit** [mikacuy/pointnetvlad#5]
Hi, thanks for your code. I have a question regarding the datasets you are using to generate the training tuples. In the file [generate_training_tuples_baseline.py](generating_queries/generate_training_tuples_baseline.py), line 21, `index_list=range(len(all_folders)-1) ` , it seems that you are using all runs except for the last sequence. Any reason for this? Or did I miss something?
Thanks for your help in advance!

**Comment by mikacuy** [comment]
Hi,

I apologize for the delayed response. The experiments were ran for all sequences. That code can be modified to fit your file arrangements. Thanks
