### ISSUE TITLE
Cannot find groundplane fitting code

### ISSUE THREAD

**Issue by kxhit** [mikacuy/pointnetvlad#6]
Hi! Thanks for sharing your code!
I couldn't find the source code of removing ground plane (e.g. `pcfitplane`). Could you give me some guidance? Is there something wrong? Thanks!
Looking forward to your reply!

**Comment by mikacuy** [comment]
Hi,

Here is the link to MATLAB's pcfitplane function: https://www.mathworks.com/help/vision/ref/pcfitplane.html

Hope this helps.
