### ISSUE TITLE
Different timestamps for Oxford dataset when generating submaps

### ISSUE THREAD

**Issue by sashaDoubov** [mikacuy/pointnetvlad#8]
Hi, thanks for your great work! I am trying to use the script `generate_submaps.m` to recreate the benchmark dataset for the Oxford Robotcar dataset. However, I seem to get different pointclouds (as described by the timestamps) than the ones found in the uploaded benchmarks folder on google drive. 

For example, for the `2015-08-17-10-26-38` folder, the `1439803802060497.bin` pointcloud cannot be found after generating the submaps, with the closest generated timestamps being: `1439803802982745.bin` and `1439803801699224.bin`. 

There is some overlap between the generated and posted pointclouds for the same `2015-08-17-10-26-38` folder, such as: `1439803985022188.bin`  and `1439803989723175.bin`.

I have not modified the uploaded script except for path changes, and am using the default values for the following parameters:
```    
submap_cover_distance=20.
laser_reading_distance=0.025;
laser_reading_angle=30;
dist_start_next_frame=10.0;
```

Are there any parameter changes that need to be made to get the generated timestamps & pointclouds to correspond? Thank you!

**Comment by mikacuy** [comment]
Hi,

I apologize for the late response. If I remember correctly, those were the parameters I used to generate the submaps. I am also not sure why you get a different timestamp. Sorry about that if this doesn't help.

Best,
Mika
