### ISSUE TITLE
"Failed to find any matching files for log/model.ckpt"

### ISSUE THREAD

**Issue by roycyh** [mikacuy/pointnetvlad#9]
Hi, @mikacuy  may I ask how to solve this problem? It seems there is no file named `model.ckpt`. I only found `model_baseline.ckpt.index` and `model_refine.ckpt.index` from the downloaded pre-trained model.

`2019-12-21 18:46:13.067473: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for log/model.ckpt`

Thanks.

**Comment by mikacuy** [comment]
Hi,

Please change "model.ckpt" to either model_baseline.ckpt or model_refine.ckpt depending on which you want to test out.

Thanks,
Mika
